### ISSUE TITLE
complexity scores

### ISSUE THREAD

**Issue by alhafidzhamdan** [AmpliconSuite/AmpliconClassifier#11]
Hi @jluebeck,

Saw your biorxiv paper recently https://www.biorxiv.org/content/10.1101/2022.07.25.501144v1.full.pdf#page=10&zoom=auto,-271,691 ; congrats!

I was wondering which column should one take as the "complexity score" from AmpliconClassifier output's *feature_entropy.tsv file? Is it the "total_feature_entropy" ? Or does one have to do some additional summation?

Thanks 
Al

**Comment by jluebeck** [comment]
Hi Al,

Thanks for the query - I just updated the documentation in [9e1a175](https://github.com/jluebeck/AmpliconClassifier/commit/9e1a1753a85d6118c89300cde8aedfbb21fb7b73) to provide additional descriptions of the output files. Please let me know if you have additional questions.

Jens

**Comment by alhafidzhamdan** [comment]
Got it- thanks!
