### ISSUE TITLE
No [prefix]_feature_entropy.tsv files in AC output?

### ISSUE THREAD

**Issue by edceeyuchen** [AmpliconSuite/AmpliconClassifier#16]

**Comment by jluebeck** [comment]
Hi, thanks for reaching out. Can you provide a bit more context, such as version number of AC you are using and whether this is being used through one of the web interfaces?

In versions of AC prior to 0.5.0, these files were not generated by default, and to get them you must set `--report_complexity`

Thanks,
Jens

**Comment by edceeyuchen** [comment]
> Hi, thanks for reaching out. Can you provide a bit more context, such as version number of AC you are using and whether this is being used through one of the web interfaces?
> 
> In versions of AC prior to 0.5.0, these files were not generated by default, and to get them you must set `--report_complexity`
> 
> Thanks, Jens

Thank you jluebeck! I have solved the problem by add --report_complexity, maybe it could show in README so that explain this clearly?  But sorry, it's also my easy mistakes
