### ISSUE TITLE
Can AmpliconClassifier output the classification of each Cycle in the "*_amplicon_cycles.txt" file?

### ISSUE THREAD

**Issue by kerenzhou062** [AmpliconSuite/AmpliconClassifier#2]
Hi Jens,

Can you make AmpliconClassifier output the classification of each Cycle in the "*_amplicon_cycles.txt" file?

Best,
Keren

**Comment by jluebeck** [comment]
Hi Keren,

I will certainly consider this. Perhaps something that writes a new cycles
file including annotations about whether each path/cycle conforms to
ecDNA-like, BFB-like, or other. Is this what you had in mind?

Best,
Jens

**Comment by kerenzhou062** [comment]
Hi Jens,

Yes, that's what I had in mind. It can be written in the new annotation file and the format may be just like bellow:

Cycle=1;Copy_count=#float;Class=circular
Cycle=2;Copy_count=#float;Class=BFB-like

Of course, you can do it in your own way.

Thanks,
Keren

**Comment by kerenzhou062** [comment]
Hi Jens,

When will this new functionality of AmpliconClassifier  be available for download?

Best,
Keren

**Comment by jluebeck** [comment]
Hi Keren,

Apologies, but I have not had time to work on this specific feature. I'd also draw your attention to `--report_genes` flag, which will output a bed file of the ecDNA (or BFB) regions of the AA amplicons which are predicted to contain ecDNA. While it does not tag specific cycles as ecDNA-like, you can determine which regions contain ecDNA-like cycles.

Best regards,
Jens

**Comment by kerenzhou062** [comment]
> Hi Keren,
> 
> Apologies, but I have not had time to work on this specific feature. I'd also draw your attention to `--report_genes` flag, which will output a bed file of the ecDNA (or BFB) regions of the AA amplicons which are predicted to contain ecDNA. While it does not tag specific cycles as ecDNA-like, you can determine which regions contain ecDNA-like cycles.
> 
> Best regards,
> Jens

Hi Jens,

I've checked the results from `--report_genes`, but it does not really feed my needs. Could you please develop this feature sooner or later? It'll really help a lot on my present project.

Thanks!
Keren

**Comment by jluebeck** [comment]
Hi Keren,

I have added a feature which will annotate the cycles file. It creates a new cycles file, which contains some annotations about size, classification type, etc. of the amplicon.  You can do `--annotate_cycles_file` to turn it on when you run AC.

Best,
Jens

**Comment by kerenzhou062** [comment]
> Hi Keren,
> 
> I have added a feature which will annotate the cycles file. It creates a new cycles file, which contains some annotations about size, classification type, etc. of the amplicon. You can do `--annotate_cycles_file` to turn it on when you run AC.
> 
> Best,
> Jens

Hi Jens,

I've tried this new feature, and that's what I want!

Thank you so much!

Best,
Keren

**Comment by KR-Chow** [comment]
> Hi Keren,
> 
> I have added a feature which will annotate the cycles file. It creates a new cycles file, which contains some annotations about size, classification type, etc. of the amplicon. You can do `--annotate_cycles_file` to turn it on when you run AC.
> 
> Best,
> Jens

Hi Jens,

In the `amplicon_classifier.py`, can I change the `padding` variable into 200000 or something when determining whether a cycle is ecDNA-like? The position of the variable is as below:
`
def clusterECCycles(cycleList, cycleCNs, segSeqD, excludableCycleIndices=None):
    padding = 500000
`
