### ISSUE TITLE
how to compare with CIRCLE-seq

### ISSUE THREAD

**Issue by SeqCrafter** [AmpliconSuite/AmpliconClassifier#5]
after running AA and AC,I konw I got some amplication with eccDNA. However, in fact, a cycle defined in one amplicon of AA may contain multiple segments. However, when we run Circle-Map on CIRCLE-seq data, we usually get a self closed cycle with only one segment. What data should I use to compare with the circleseq data?

**Comment by jluebeck** [comment]
This is a very hard question for me to answer without seeing the data itself, sorry. Please feel free to email me if you would like to discuss further.

Best regards,
Jens
