### ISSUE TITLE
Feature Request: Change Directory of uploads

### ISSUE THREAD

**Issue by Toseph** [AmpliconSuite/AmpliconClassifier#6]
It would be beneficial if the directory for uploads could be modified using an environment variable or argument to ampliconClassifier.

**Comment by jluebeck** [comment]
Hi,

Thank you for your suggestion. I have changed AC so that the argument `-o` also controls the prefix of the directories created by AC. If you had a different suggestion in mind please let me know. Changes are available in 0.4.2.

Best,
Jens
